# Generated by Django 4.2.11 on 2025-10-11 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FortuneFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('feature_type', models.CharField(choices=[('coffee_fortune', 'Coffee Fortune Reading'), ('feng_shui', 'Feng Shui Analysis'), ('dream_interpretation', 'Dream Interpretation'), ('birthdate_horoscope', 'Birthdate Horoscope'), ('tarot', 'Tarot Reading'), ('numerology', 'Numerology'), ('palm_reading', 'Palm Reading')], max_length=50, unique=True)),
                ('input_type', models.CharField(choices=[('text', 'Text Input'), ('image', 'Image Input'), ('text_image', 'Text and Image Input')], max_length=20)),
                ('description', models.TextField()),
                ('prompt_template', models.TextField(help_text='Template for the prompt. Use {user_input} and {image_description} as placeholders.')),
                ('is_active', models.BooleanField(default=True)),
                ('model_name', models.CharField(default='openai/gpt-4o-mini', help_text='OpenRouter.ai model identifier', max_length=100)),
                ('max_tokens', models.IntegerField(default=1000)),
                ('temperature', models.FloatField(default=0.7)),
                ('credit_cost', models.IntegerField(default=1, help_text='Credits required per reading')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fortune Feature',
                'verbose_name_plural': 'Fortune Features',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_input', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='readings/%Y/%m/%d/')),
                ('interpretation', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, max_length=100, null=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(default=0, help_text='Processing time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='fortune.fortunefeature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reading',
                'verbose_name_plural': 'Readings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, help_text='User rating from 1-5', null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fortune.fortunefeature')),
                ('reading', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='fortune.reading')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reading History',
                'verbose_name_plural': 'Reading Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
